[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nftmarketplace = "CGTG4etJpxd39CQp9nMRsVAwPT6P58zQF9XfT8zw6GhW"

[programs.devnet]
nftmarketplace = "CGTG4etJpxd39CQp9nMRsVAwPT6P58zQF9XfT8zw6GhW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/NFT-Marketplace.json"

[scripts]
test = "yarn test"
